config/routes.rb
DataKraken::Application.routes.draw do

  get '/auth/:provider/callback', to: 'oauth_consumers#callback'
  get '/auth/:provider/callback2', to: 'oauth_consumers#callback'

  resources :oauth_consumers, only: [:index]

  resources :missions do
    get "run_now"
    post "activate"
    post "deactivate"
    get "graph_file"
    get "prepare_database"
    get "cleanup_database"
    post "sidekiq_control"
    get "data_import_events", {controller: "explorer_infos", action: "data_import"}
    get "last_data_import_events", {controller: "explorer_infos", action: "data_import", limit: 5}
  end

  resources :explorers do
    get "events", {controller: "explorer_infos", action: "explorer"}
    get "last_events", {controller: "explorer_infos", action: "explorer", limit: 5}
    get "run_now"
  end

  resources :mappings do
    get :preview
    get :mk
  end

  resources :mapping_keys, only: [:update, :destroy] do
    post "add_field"
    post "remove_field"
  end

  devise_for :users
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  root to: "missions#index"
end

app/controllers/oauth_consumers_controller.rb
class OauthConsumersController < ApplicationController
  before_filter :authenticate_user!, :only=>:index

  def index
    @connected_services = ConsumerToken.all(:conditions => {:user_id => current_user.id}).collect{|ct| ct.provider}
    @available_services = OAUTH_CREDENTIALS.keys.collect{|oap| oap.to_s} - @connected_services
  end

  def callback
    @consumer_token = current_user.consumer_tokens.where(:provider => params[:provider]).first
    @consumer_token ||= current_user.consumer_tokens.create(:provider => params[:provider])
    @consumer_token.token = auth_hash[:credentials][:token]
    @consumer_token.secret = auth_hash[:credentials][:secret]
    @consumer_token.save
    redirect_to oauth_consumers_path, :notice => "Successfully connected to #{params[:provider]}"
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/views/oauth_consumers/index.html.erb
<h1>Services</h1>

<% if @connected_services.empty? %>
  <p>
    You are currently not connected to any external services.
  </p>
<% else %>
  <p>
    You are connected to the following services:
  </p>
  <ul class="inline">
    <% @connected_services.each do |provider| %>
      <li>
        <%= link_to provider.to_s.humanize, "/auth/#{provider}", :class => "btn btn-success" %>
      </li>
    <% end %>
  </ul>
<% end %>

<% unless @available_services.empty? %>
<h3>You can connect to the following services:</h3>
<ul class="inline">
  <% @available_services.each do |provider| %>
    <li>
      <%= link_to provider.to_s.humanize, "/auth/#{provider}", :class => "btn btn-danger" %>
    </li>
  <% end %>
</ul>
<% end %>

app/views/oauth_consumers/show.html.erb
<h1>You are already Connected to <%=params[:id].humanize%></h1>
<% form_tag oauth_consumer_path(params[:id]),:method=>:delete do %>
  <%=submit_tag "Disconnect" %>
  or
  <%=submit_tag "Reconnect" %>
  if you experienced a problem.
<% end %>