config/routes.rb
DataKraken::Application.routes.draw do

  get '/auth/:provider/callback', to: 'oauth_consumers#callback'
  get '/auth/:provider/callback2', to: 'oauth_consumers#callback'

  resources :oauth_consumers, only: [:index]

  resources :missions do
    get "run_now"
    post "activate"
    post "deactivate"
    get "graph_file"
    get "prepare_database"
    get "cleanup_database"
    post "sidekiq_control"
    get "data_import_events", {controller: "explorer_infos", action: "data_import"}
    get "last_data_import_events", {controller: "explorer_infos", action: "data_import", limit: 5}
  end

  resources :explorers do
    get "events", {controller: "explorer_infos", action: "explorer"}
    get "last_events", {controller: "explorer_infos", action: "explorer", limit: 5}
    get "run_now"
  end

  resources :mappings do
    get :preview
    get :mk
  end

  resources :mapping_keys, only: [:update, :destroy] do
    post "add_field"
    post "remove_field"
  end

  devise_for :users
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  root to: "missions#index"
end

app/models/mapping.rb
class Mapping < ActiveRecord::Base
  # relations
  has_many :mapping_keys, dependent: :destroy
  # we can be a mapping for a single explorer
  belongs_to :explorer
  # or the blueprint for all of them
  belongs_to :explorer_description

  # attributes
  attr_accessible :name, :description, :default_key, :opt_in

  def is_valid?
    keys_valid = !mapping_keys.empty? && mapping_keys.all?{|mk| mk.is_valid?}
    pk_mappings = mapping_keys.where("key LIKE '%?'", default_key)
    # check if default_key is not ignored if opt_in is used
  end

  # transform into a hash. This avoids DB lookups and simplifies the implementation of datastores
  def hashify
    mapping_hash = {:default_key => self.default_key}
    mapping_keys.each{|mk| mapping_hash.merge!(mk.hashify)}
    return mapping_hash
  end

  def alternatives
    # if we are a "general" mapping that does not belong anywhere, no alternatives
    explorer.nil? ? [] : explorer_description.mappings - [self]
  end

  def sample_with_html
    json = sample_json
    indexed_keys = [nil] + follow_hash("", json) + [nil]
    pretty_lines = []
    JSON.pretty_generate(json).lines.each_with_index do |line, i|
      if indexed_keys[i].nil?
        pretty_lines << strip_html(line)
      else
        pretty_lines << "<span data-full-key=\"#{indexed_keys[i]}\">#{strip_html(line)}</span>"
      end
    end
    return pretty_lines.join("")
  end

  def strip_html(str)
    ActionView::Base.full_sanitizer.sanitize(str)
  end

  def sample_json
    JSON.parse(File.open(explorer_description.sample_file).read)
  end

  def follow_hash(key_so_far, json)
    keys = []
    json.each_pair do |k, v|
      next_key = key_so_far.blank? ? k : "#{key_so_far}.#{k}"
      keys << next_key
      if v.is_a?(Array) && v.first.is_a?(Hash)
        keys << nil
        keys.concat(follow_hash(next_key, v.first))
        keys.concat([nil,nil])
      elsif v.is_a?(Array)
        (v.size + 1).times{keys << nil}
      elsif v.is_a?(Hash)
        keys.concat(follow_hash(next_key, v))
        keys << nil
      end
    end
    return keys
  end

  def keys_for(mk)
    direct_mappings = mapping_keys.where(key: mk)
    regexp_mappings = mapping_keys.where(is_regexp: true).select{|mapping_entry|
      regexp = Regexp.new(mapping_entry.key)
      mk.match(regexp)
    }
    return direct_mappings + regexp_mappings
  end

  def default_options
    sample_json.keys
  end

  def possible_move_targets(key)
    get_object_keys("", sample_json) - [key]
  end

  def get_object_keys(key_so_far, json)
    keys = []
    keys << key_so_far if json.is_a?(Hash)
    json.each_pair do |k,v|
      next_key = key_so_far.blank? ? k : "#{key_so_far}.#{k}"
      next_obj = v.is_a?(Array) ? v.first : v
      keys.concat(get_object_keys(next_key, next_obj)) if next_obj.is_a?(Hash)
    end
    return keys
  end

  def possible_primary_keys(key)
    json = sample_json
    key.split(".").each{|subkey| json = json[subkey]}
    json = json.first if json.is_a?(Array)
    if json.nil?
      return []
    else
      return json.keys
    end
  end

  def update_preview_graph
    ds = DataStore.new(self)
    x = Time.now
    ds.load_sample
    g = GraphViz.new("#{id}", {:type => :digraph, :splines => :true, rankdir: "LR"})
    node_cache = {}
    node_types = ds.nodes.collect{|n| n.type}.uniq
    palette = Paleta::Palette.generate(:type => :random, :size => node_types.size)

    ds.nodes.each_with_index do |node, i|
      node_cache[node] = g.add_node(i.to_s, {
        label: node.label_string,
        shape: :record,
        color: "##{palette[node_types.index(node.type)].hex}",
        fontsize: 35,
        penwidth: 4,
        style: :rounded
      })
    end
    ds.nodes.each do |node|
      node.all_relations.each do |rel|
        g.add_edge(node_cache[rel.source], node_cache[rel.target], {
          label: rel.name, labelfloat: false, fontsize: 30, labeldistance: 30.0, penwidth: 3
          })
      end
    end
    g.output(:png => preview_file_path)
    return true
  end

  def delete_preview_graph
    File.delete(preview_file_path) if File.exist?(preview_file_path)
  end

  def preview_file_path
    "public/mapping_previews/#{id}.png"
  end

  def preview_image_path
    "/mapping_previews/#{id}.png"
  end
end

app/controllers/mappings_controller.rb
class MappingsController < ApplicationController

  def preview
    @mapping = Mapping.find(params[:mapping_id])
    begin
      @mapping.delete_preview_graph
      @mapping.update_preview_graph
    rescue Exception => e
      @mapping_error = e.message
    end
    render layout: false
  end

  def update
    mapping = Mapping.find(params[:id])
    # load the template if the user selected this option
    if params[:load_template]
      mapping = mapping.explorer.replace_mapping(Mapping.find(params[:replacement_mapping_id]))
    else
      mapping.update_attributes(params[:mapping])
    end
    redirect_to mapping
  end

  def show
    @mapping = Mapping.find(params[:id])
    @explorer = @mapping.explorer
  end

  def mk
    mapping = Mapping.find(params[:mapping_id])
    highlighted = mapping.keys_for(params[:key])

    if highlighted.empty?
      new_key = mapping.mapping_keys.create(key: params[:key])
      render partial: "mapping_key", locals: {mk: new_key} and return
    else
      render json: highlighted.collect{|mk| "mapping-entry-#{mk.id}"}
    end
  end
end

app/helpers/mappings_helper.rb
module MappingsHelper

  def field_for_mapping_option(attrib, val, f, mk)
    send("field_for_#{attrib}".to_sym, attrib, val, f, mk)
  end

  def field_for_ignore(attrib, val, f, mk)
    f.check_box(attrib, class: "mapping-checkbox")
  end

  def field_for_type_name(attrib, val, f, mk)
    f.text_field(attrib, class: "input-small")
  end

  def field_for_move_to(attrib, val, f, mk)
    f.select(attrib, options_for_select(mk.possible_move_targets,val),{},{class: "input-small"})
  end

  def field_for_primary_key(attrib, val, f, mk)
    f.select(attrib, options_for_select(mk.possible_primary_keys,val), {}, {class: "input-small"})
  end

  def field_for_datatype(attrib, val, f, mk)
    f.select(attrib, options_for_select(MappingKey::DATATYPES, val), {}, {class: "input-medium"})
  end

  def field_for_rename_to(attrib, val, f, mk)
    f.text_field(attrib, class: "input-small")
  end

  def field_for_foreign_key(attrib, val, f, mk)
    f.text_field(attrib, class: "input-small")
  end

  def field_for_no_updates(attrib, val, f, mk)
    f.check_box(attrib, class: "mapping-checkbox")
  end

  def field_for_no_inserts(attrib, val, f, mk)
    f.check_box(attrib, class: "mapping-checkbox")
  end
  
  def field_for_no_relation(attrib, val, f, mk)
    f.check_box(attrib, class: "mapping-checkbox")
  end  
end

app/views/mappings/_mapping_key.html.erb
<div class="mapping-key" data-full-key="<%= mk.key %>" id="mapping-entry-<%= mk.id %>">
  <div style="float: right; padding-right: 5px;">
    <%= button_tag(onclick: "highlight_both('#{mk.key}', #{mk.id})", class: "btn btn-mini") do %>
      <%= fa_icon("search")%>
    <% end %>
    <%= link_to(
      fa_icon("times-circle"),
      mapping_key_path(mk),
      method: :delete, remote: true,
      class: "closer btn btn-mini update-me",
      confirm: "Really delete mapping for '#{mk.key}'?"
    )%>
  </div>

  <%= form_for(mk, remote: true, html: {class: "no-space update-me edit_mapping_key"}) do |f|%>
  <div>
    <span style="font-style: italic;" onclick="display_key_edit($(this));"><%= mk.display_key %></span>
    <%= f.text_field(:key, {value: mk.display_key, class: "input-medium", style: "display: none", autocomplete: "off"}) %>
  </div>
  <div>
    <% mk.hash_style_mapping.each_pair do |attrib, val| %>
      <div class="input-prepend">
      <span class="add-on">
      <%= link_to(
            fa_icon("times-circle"),
            mapping_key_remove_field_path(mk, field: attrib),
            remote: true, method: :post, class: "closer update-me"
          )
      %>
      <%= attrib %>
      </span>
      <%= field_for_mapping_option(attrib, val, f, mk) %>
      </div>
    <% end %>
  <% end %>
  </div>

  <% unless mk.unset_attributes.empty? %>
    <hr style="margin-top: 0px; margin-bottom: 5px;" />
    <div>
      <%= form_tag(mapping_key_add_field_path(mk), remote: true, class: "no-space update-me") do %>
        <%= select_tag(:new_field, options_for_select(mk.unset_attributes), class: "input-medium") %>
        <%= button_tag(type: 'submit', class: "btn btn-mini") do %><%= fa_icon("plus-circle", class: "success") %><% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/mappings/preview.html.erb
<div id="mapping-preview-<%= @mapping.id %>" class="modal hide preview_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <% if @mapping_error.nil? %>
        <%= image_tag(@mapping.preview_image_path)%>
      <% else %>
        <%= "Could not create preview: <strong>#{@mapping_error}</strong>".html_safe %>
      <% end %>
    </div>
  </div>
</div>

app/views/mappings/show.html.erb
<h3>
  Mapping for
  <%= link_to(@explorer.identifying_name, @explorer) %>
  of Mission
  <%= link_to(@explorer.mission.name, @explorer.mission)%>
</h3>

<div class="span12" style="margin-left: 0px;">
  <div id="mapping-<%= @mapping.id %>">
  <%= form_for(@mapping, html: {class: "form-inline"}) do |f| %>

    <% unless @mapping.alternatives.empty? %>
    <div class="input-append">
      <%= select_tag(:replacement_mapping_id, options_from_collection_for_select(@mapping.alternatives, "id", "name")) %>
      <%= submit_tag("Load Template", class: "btn btn-danger", name: "load_template") %>
    </div>
    &nbsp;|&nbsp;
    <% end %>

    <div class="input-prepend">
      <span class="add-on"><%= f.label(:name)%></span>
      <%= f.text_field(:name, :placeholder => "Pick a speaking name", class: "input-medium")%>
    </div>
    <div class="input-prepend">
      <span class="add-on"><%= f.label(:default_key)%></span>
      <%= f.select(:default_key, options_for_select(@mapping.default_options, @mapping.default_key), {}, {class: "input-small"})%>
    </div>
    <%= f.label("Opt In?", :class => "checkbox inline") %>
    <%= f.check_box(:opt_in) %>

    <%= submit_tag("Save", class: "btn btn-success", style: "margin-left: 10px", name: "save") %>
    <%= link_to("Graph Preview", mapping_preview_path(@mapping), class: "btn btn-info show-preview-btn", remote: true)%>
  <% end %>
  </div>

  <div class="span7" style="margin-left: 10px; margin-top: 10px;">
  <pre class="json-view" data-update-url="<%= mapping_mk_path(@mapping) %>"><%= @mapping.sample_with_html.html_safe %></pre>
  </div>

  <div class="span5" id="mapping-list" style="margin-left: 10px;">
    <% @mapping.mapping_keys.sort_by{|a| a.key}.each do |mk| %>
      <%= render partial: "mappings/mapping_key", locals: {mk: mk}%>
    <% end %>
  </div>

  <div id="mapping-preview-<%= @mapping.id %>"></div>
</div>