config/routes.rb
DataKraken::Application.routes.draw do

  get '/auth/:provider/callback', to: 'oauth_consumers#callback'
  get '/auth/:provider/callback2', to: 'oauth_consumers#callback'

  resources :oauth_consumers, only: [:index]

  resources :missions do
    get "run_now"
    post "activate"
    post "deactivate"
    get "graph_file"
    get "prepare_database"
    get "cleanup_database"
    post "sidekiq_control"
    get "data_import_events", {controller: "explorer_infos", action: "data_import"}
    get "last_data_import_events", {controller: "explorer_infos", action: "data_import", limit: 5}
  end

  resources :explorers do
    get "events", {controller: "explorer_infos", action: "explorer"}
    get "last_events", {controller: "explorer_infos", action: "explorer", limit: 5}
    get "run_now"
  end

  resources :mappings do
    get :preview
    get :mk
  end

  resources :mapping_keys, only: [:update, :destroy] do
    post "add_field"
    post "remove_field"
  end

  devise_for :users
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  root to: "missions#index"
end

app/models/mission.rb
class Mission < ActiveRecord::Base
  attr_accessible :name, :description, :target_server, :interval, :database_name, :target_data_store, :username, :password
  as_enum :target_data_store, %i{mongo_db neo4j hana_graph gravity hana}

  belongs_to :user
  has_many :explorers, :dependent => :destroy
  validates :user, :presence => true
  validates :target_server, :presence => true

  before_destroy :teardown_sidekiqs

  ALWAYS = 0
  HOURLY = 60
  TWICE_A_DAY = 720
  DAILY = 1440

  SIDEKIQS = ["data_import", "explorers", "explorer_tasks"]

  def should_run_now?
    if self.interval == ALWAYS || last_run.nil?
      return true
    else
      return (Time.now - last_run) > (self.interval * 60)
    end
  end

  def launch_explorers!
    explorers.each{|explorer| explorer.enqueue!}
    self.last_run = DateTime.now
    self.save
  end

  def unique_name
    "#{name}_#{id}"
  end

  def prepare_database
    explorers.each{|explorer| explorer.prepare_database}
  end

  def cleanup_database
    explorers.each{|explorer| explorer.cleanup_database}
  end

  def start_sidekiq(which_one)
    Dir.chdir(Rails.root.to_s) do
      target_path = sidekiq_config(which_one)
      adapt_template_config(default_config(which_one), target_path) unless File.exist?(target_path)
      system("bundle exec sidekiq -C #{sidekiq_config(which_one).to_s} -d")
    end
  end

  def teardown_sidekiqs
    SIDEKIQS.each do |sidekiq|
      FileUtils.rm_rf(sidekiq_config(sidekiq))
      stop_sidekiq(sidekiq)
      Sidekiq::Queue.new(sidekiq_queue(sidekiq)).clear
    end
    return true
  end

  def stop_sidekiq(which_one)
    Dir.chdir(Rails.root.to_s) do
      system("bundle exec sidekiqctl stop tmp/pids/sidekiq_#{which_one}_#{id}.pid")
    end
    return true
  end

  def adapt_template_config(template_file, target_path)
    template = File.open(template_file).read
    template.gsub!("<% mission_id %>", "#{id}")
    File.open(target_path,"w+"){|f| f.puts template}
  end

  def default_config(which_one)
    "config/sidekiq/#{which_one}.yml.default"
  end

  def sidekiq_config(which_one)
    "config/sidekiq/#{which_one}_#{id}.yml"
  end

  def sidekiq_queue(which_one)
    "mission_#{id}_#{which_one}"
  end

  def explorer_queue()
    sidekiq_queue("explorers")
  end

  def data_import_queue()
    sidekiq_queue("data_import")
  end

  def explorer_task_queue
    sidekiq_queue("explorer_tasks")
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_filter :authenticate_user!, :except => [:graph_file]

  def show
    @mission = Mission.find(params[:id])
    @descriptions = ExplorerDescription.all
    @title = "Mission Overview - '#{@mission.name}'"
    flash[:notice] = "No explorers configured. Please add some to your job!" if @mission.explorers.empty?
  end

  def index
    @missions = current_user.missions
    if @missions.blank?
      redirect_to new_mission_path(), {:notice => "No missions available, create one, young explorer!"}
    end
  end

  def destroy
    @mission = Mission.find(params[:id])
    if @mission.destroy
      redirect_to missions_path, {:notice => "Mission #{params[:id]} successfully deleted."}
    else
      redirect_to missions_path, {:alert => "Mission #{params[:id]} could not deleted."}
    end
  end

  def create
    @mission = current_user.missions.build(params[:mission])
    if @mission.save
      redirect_to @mission, :notice => 'Mission was successfully created.'
    else
      render :action =>  "new"
    end
  end

  def new
    @mission = Mission.new()
  end

  def run_now
    @mission = Mission.find(params[:mission_id])
    @mission.launch_explorers!
    redirect_to @mission, :notice => "Activated inactive explorers instantly!"
  end

  def activate
    @mission = Mission.find(params[:mission_id])
    @mission.active = true
    @mission.save
    redirect_to :action => :index
  end

  def deactivate
    @mission = Mission.find(params[:mission_id])
    @mission.active = false
    @mission.save
    redirect_to :action => :index
  end

  def update
    @mission = Mission.find(params[:id])
    if @mission.update_attributes(params[:mission])
      redirect_to @mission, :notice => 'Mission was successfully updated.'
    else
      redirect_to @mission, :alert => 'Mission could not be updated.'
    end
  end

  def edit
    @mission = Mission.find(params[:id])
  end

  def graph_file
    @mission = Mission.find(params[:mission_id])
    if @mission.target_data_store == :gravity
      send_file @mission.explorers.first.data_store.graph_file, type: Mime::JSON
    else
      redirect_to @mission and return
    end
  end

  def prepare_database
    @mission = Mission.find(params[:mission_id])
    begin
      @mission.prepare_database
      redirect_to @mission, :notice => 'Database was successfully prepared.'
    rescue Exception => e
      redirect_to @mission, :alert => "Error during database initialization: #{e.message}"
    end
  end

  def cleanup_database
    @mission = Mission.find(params[:mission_id])
    begin
      @mission.cleanup_database
      redirect_to @mission, :notice => 'Database was successfully cleansed.'
    rescue Exception => e
      redirect_to @mission, :alert => "Error during database initialization: #{e.message}"
    end
  end

  def sidekiq_control
    @mission = Mission.find(params[:mission_id])
    sidekiqs = params[:sidekiqs] == "all" ? Mission::SIDEKIQS : [params[:sidekiqs]]
    begin
      sidekiqs.each do |sk|
        @mission.start_sidekiq(sk) if params[:start]
        @mission.stop_sidekiq(sk) if params[:stop]
      end

      redirect_to @mission, :notice => "Sidekiqs (#{sidekiqs.join(', ')}) have been #{params[:start] || params[:stop]}ed."
    rescue Exception => e
      redirect_to @mission, :alert => "Error during sidekiq initialization: #{e.message}"
    end
  end
end

app/helpers/missions_helper.rb
module MissionsHelper
  def interval_options
    [[t(:always), Mission::ALWAYS], [t(:hourly), Mission::HOURLY], [t(:twice_a_day), Mission::TWICE_A_DAY], [t(:daily), Mission::DAILY]]
  end

  def sidekiq_options
    opts = Mission::SIDEKIQS.collect{|optn| [optn, optn]} + ["all"]
    options_for_select(opts)
  end
end

app/views/missions/_form.html.erb
<%= form_for(mission, :html => {:class => "form-horizontal"}) do |f| %>
<div class="control-group">
  <%= f.label :name, :class => "control-label" %>
  <div class="controls">
  <%= f.text_field :name %>
  </div>
</div>
<div class="control-group">
  <%= f.label :description, :class => "control-label" %>
  <div class="controls">
  <%= f.text_area :description, :rows => 5 %>
  </div>
</div>
<div class="control-group">
  <%= f.label :database_url, :class => "control-label" %>
  <div class="controls">
  <%= f.text_field :target_server %>
  </div>
</div>
<div class="control-group">
  <%= f.label :database_name, :class => "control-label" %>
  <div class="controls">
  <%= f.text_field :database_name %>
  </div>
  <%= f.label :database_username, :class => "control-label" %>
  <div class="controls">
  <%= f.text_field :username %>
  </div>
  <%= f.label :database_password, :class => "control-label" %>
  <div class="controls">
  <%= f.password_field :password %>
  </div>
</div>
<div class="control-group">
  <%= f.label :which_database?, :class => "control-label" %>
  <div class="controls">
    <%= f.select(:target_data_store, Mission.target_data_stores.keys) %>
  </div>
</div>
<div class="control-group">
  <%= f.label :run_when?, :class => "control-label" %>
  <div class="controls">
  <%= f.select(:interval, options_from_collection_for_select(interval_options(), "last", "first", mission.interval)) %>
  </div>
</div>

<%= f.submit("Save", :class => "btn btn-success") %>
<%= link_to("Cancel", missions_path, :class => "btn btn-danger") %>
<% end %>

app/views/missions/_mission_status.html.erb
<h4>Mission Status</h4>
<br />
<% @mission.explorers.order("created_at ASC").each do |explorer| %>
  <%= link_to(explorer.identifying_name, explorer_events_path(explorer)) %>
  <div class="explorer-info-div" data-callback-url="<%=explorer_last_events_path(explorer.id)%>"></div>
  <hr />
<% end %>
<%= link_to("Data Import", mission_data_import_events_path(@mission)) %>
<div class="explorer-info-div" data-callback-url="<%=mission_last_data_import_events_path(@mission.id)%>"></div>
<hr />

app/views/missions/edit.html.erb
<%= render :partial => "form", :locals => {:mission => @mission} %>

app/views/missions/index.html.erb
<h3>Your Mission overview</h3>
<table class="table table-hover">
  <tr>
    <th>Name</th>
    <th>Active?</th>
    <th>Actions</th>
  </tr>
  <% @missions.each do |mission| %>
  <tr>
    <td><%= mission.name %><br /><small><%= mission.description %></small></td>
    <td><%= image_tag(mission.active ? "icons/bullet_green.png" : "icons/bullet_red.png", :size => "25x25")%></td>
    <td>
      <%= link_to("Activate", mission_activate_path(mission), {:class => "btn btn-primary", :method => :post}) %>
      <%= link_to("Deactivate", mission_deactivate_path(mission), {:class => "btn btn-warning", :method => :post}) %>
      <%= link_to("Administrate", mission_path(mission), :class => "btn btn-info") %>
      <%= link_to("Delete", mission_path(mission), {:class => "btn btn-danger", :confirm => "Sure?", :method => :delete}) %>
    </td>
  </tr>
  <% end %>
  <tr>
    <td colspan="3"><%= link_to("New Mission", new_mission_path() ,:class => "btn btn-success")%></td>
  </tr>
</table>

app/views/missions/new.html.erb
<%= render 'application/errors', object: @mission %>
<h4>Create a new data collection job</h4>
<%= render :partial => "form", :locals => {:mission => @mission} %>

app/views/missions/show.html.erb
<div class="span8">
  <h4 class="text-info"><em><%= @mission.name %></em></h4>
  <small>Last run: <%= @mission.last_run.nil? ? "n/a" : @mission.last_run %></small>

  <div>
  <%= link_to("Edit Mission", edit_mission_path(@mission), :class => "btn")%>
  <%= link_to("Run all Explorers!", mission_run_now_path(@mission), :class => "btn btn-primary")%>
  <%= link_to("Initialize DB", mission_prepare_database_path(@mission), :class => "btn btn-success")%>
  <%= link_to("Cleanup DB", mission_cleanup_database_path(@mission), :class => "btn btn-success")%>
  <%= form_tag(mission_sidekiq_control_path(@mission), class: "some-space") do %>
    <%= select_tag(:sidekiqs, sidekiq_options, class: "no-space")%>
    <%= submit_tag("Start", class: "btn btn-success", :name => "start")%>
    <%= submit_tag("Stop", class: "btn btn-danger", :name => "stop")%>
  <% end %>

  </div>
  <hr />

  <% unless @mission.explorers.empty?%>
  <div id="explorer_list">
    <h5>Explorers</h5>
    <% @mission.explorers.order("created_at ASC").each do |explorer| %>
      <%= render :partial => "explorers/show", :locals => {:explorer => explorer} %>
      <br />
    <% end %>
  </div>
  <% end %>

  <hr />

  <div id="add-new-ts">
    <%= render :template => "explorer_descriptions/index" %>
  </div>
</div>

<div class="span4">
  <div class="well sidebar-nav">
    <%= render :partial => "mission_status" %>
  </div>
</div>