config/routes.rb
DataKraken::Application.routes.draw do

  get '/auth/:provider/callback', to: 'oauth_consumers#callback'
  get '/auth/:provider/callback2', to: 'oauth_consumers#callback'

  resources :oauth_consumers, only: [:index]

  resources :missions do
    get "run_now"
    post "activate"
    post "deactivate"
    get "graph_file"
    get "prepare_database"
    get "cleanup_database"
    post "sidekiq_control"
    get "data_import_events", {controller: "explorer_infos", action: "data_import"}
    get "last_data_import_events", {controller: "explorer_infos", action: "data_import", limit: 5}
  end

  resources :explorers do
    get "events", {controller: "explorer_infos", action: "explorer"}
    get "last_events", {controller: "explorer_infos", action: "explorer", limit: 5}
    get "run_now"
  end

  resources :mappings do
    get :preview
    get :mk
  end

  resources :mapping_keys, only: [:update, :destroy] do
    post "add_field"
    post "remove_field"
  end

  devise_for :users
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  root to: "missions#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= @title.nil? ? "Data-Rover" : @title %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Data-Rover</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Missions", missions_path  %></li>
              <% unless current_user.nil? %>
              <li><%= link_to "Connected APIs", oauth_consumers_path %></li>
              <li><%= link_to "Background Tasks", sidekiq_web_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div>
          <%= bootstrap_flash %>
        </div>
        <div>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Epic 2013-<%= Date.today.year%></p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>